/**
 * Price data for Atelier Deniz.
 *
 * Structure:
 *   Each top-level object is a category (e.g. Naaiatelier, Stomerij).
 *   Each category contains an array of subcategories.
 *   Each subcategory has a label and an array of services with prices.
 *
 * To add / edit prices, simply update the objects below.
 */
export const tailorPriceData = [
	{
		label: 'Naaiatelier',
		subcategories: [
			{
				label: 'Colbert',
				services: [
					{ name: 'Korter/langer maken', price: '€ 20,00' },
					{ name: 'Korter/langer maken met voering', price: '€ 25,00' },
					{ name: 'Mouwen korter/langer maken', price: '€ 15,00' },
					{ name: 'Mouwen korter/langer maken met voering', price: '€ 25,00' },
					{ name: 'Mouwen korter/langer maken met split', price: '€ 25,00' },
					{ name: 'Mouwen korter/langer met knoopsgat', price: '€ 25,00' },
					{ name: 'Innemen/uitnemen zonder voering', price: '€ 20,00' },
					{ name: 'Innemen/uitnemen met voering', price: '€ 25,00' },
					{ name: 'Voering reparatie vanaf', price: '€ 11,00' },
					{ name: 'Voering inzetten vanaf en overleg', price: '€ 40,00' },
					{ name: 'Binnenzak herstellen en overleg', price: '€ 15,00' },
					{ name: 'Korter/langer maken met omslag split', price: '€ 20,00' },
				],
			},
			{
				label: 'Jack / Jas / Mantel',
				services: [
					{ name: 'Korter/langer maken', price: '€ 20,00' },
					{ name: 'Korter/langer maken met voering', price: '€ 30,00' },
					{ name: 'Korter/langer maken winterjas', price: '€ 30,00' },
					{ name: 'Mouwen korter/langer maken met voering', price: '€ 25,00' },
					{ name: 'Mouwen korter/langer maken met manchet', price: '€ 27,00' },
					{ name: 'Innemen/uitnemen zonder voering', price: '€ 25,00' },
					{ name: 'Innemen/uitnemen met voering', price: '€ 30,00' },
					{ name: 'Nieuwe rits t/m 50 cm', price: '€ 35,00' },
					{ name: 'Nieuwe rits 50 cm t/m 75 cm', price: '€ 40,00' },
					{ name: 'Nieuwe rits vanaf 80 cm', price: '€ 40,00' },
					{ name: 'Nieuwe rits leren jas', price: '€ 40,00' },
					{ name: 'Voering reparatie vanaf en overleg', price: '€ 16,00' },
					{ name: 'Voering inzetten vanaf en overleg', price: '€ 45,00' },
					{ name: 'Binnenzak herstellen en overleg', price: '€ 16,00' },
					{ name: 'Binnenzak nieuw', price: '€ 30,00' },
				],
			},
			{
				label: 'Rok & Jurk',
				services: [
					{ name: 'Korter/langer maken op afspraak tussen', price: '€ 10,00 - € 20,00' },
					{ name: 'Korter/langer maken met omslag/split', price: '€ 17,00' },
					{ name: 'Korter/langer maken met voering tussen', price: '€ 15,00 - € 25,00' },
					{ name: 'Korter/langer maken met originele zoom', price: '€ 20,00' },
					{ name: 'Mouwen korter/langer maken tussen', price: '€ 13,00 - € 20,00' },
					{ name: 'Mouwen korter/langer met voering', price: '€ 25,00' },
					{ name: 'Mouwen korter/langer met split', price: '€ 25,00' },
					{ name: 'Mouwen korter/langer met knoopsgat', price: '€ 25,00' },
					{ name: 'Zoom instikken tussen', price: '€ 10,00 - € 15,00' },
					{ name: 'Langer maken - valse zoom', price: '€ 18,00' },
					{ name: 'Innemen/uitleggen', price: '€ 20,00' },
					{ name: 'Innemen/uitleggen met voering', price: '€ 25,00' },
					{ name: 'Innemen/uitleggen met tailleband', price: '€ 25,00' },
					{ name: 'Nieuwe rits rok', price: '€ 15,00' },
					{ name: 'Nieuwe blinde rits rok', price: '€ 18,00' },
					{ name: 'Nieuwe rits jurk', price: '€ 15,00' },
					{ name: 'Nieuwe blinde rits jurk', price: '€ 20,00' },
					{ name: 'Voering reparatie overleg vanaf', price: '€ 11,00' },
					{ name: 'Voering inzetten rok vanaf', price: '€ 25,00' },
					{ name: 'Voering inzetten jurk', price: '€ 40,00' },
					{ name: 'Binnenzak herstellen overleg', price: '€ 16,00' },
				],
			},
			{
				label: 'Blouse / Overhemd',
				services: [
					{ name: 'Korter/langer maken', price: '€ 15,00' },
					{ name: 'Mouwen korter/langer maken', price: '€ 15,00' },
					{ name: 'Mouwen korter/langer met manchet', price: '€ 20,00' },
					{ name: 'Tailieren', price: '€ 15,00' },
					{ name: 'Innemen/uitleggen', price: '€ 15,00' },
					{ name: 'Opzetten van kraag', price: '€ 25,00' },
				],
			},
			{
				label: 'Pantalon / Jeans',
				services: [
					{ name: 'Korter/langer maken', price: '€ 15,00' },
					{ name: 'Korter/langer maken - valse zoom', price: '€ 15,00' },
					{ name: 'Korter/langer met omslag/split', price: '€ 20,00' },
					{ name: 'Korter/langer met voering', price: '€ 20,00' },
					{ name: 'Korter/langer met originele zoom', price: '€ 15,00' },
					{ name: 'Zoom instikken origineel', price: '€ 15,00' },
					{ name: 'Pijpen smaller maken zonder voering', price: '€ 17,00' },
					{ name: 'Pijpen smaller maken met voering', price: '€ 22,00' },
					{ name: 'Innemen/uitleggen', price: '€ 25,00' },
					{ name: 'Innemen/uitleggen met tailleband', price: '€ 25,00' },
					{ name: 'Nieuwe rits', price: '€ 15,00' },
					{ name: 'Voering reparatie', price: '€ 15,00' },
					{ name: 'Binnenzak herstellen overleg', price: '€ 20,00' },
				],
			},
			{
				label: 'Tassen',
				services: [
					{ name: 'Voering reparatie vanaf', price: '€ 8,00' },
					{ name: 'Nieuwe rits vanaf', price: '€ 25,00' },
				],
			},
			{
				label: 'Overig',
				services: [
					{ name: 'Knopen aanzetten', price: '€ 7,00' },
					{ name: 'Nieuwe runner rits', price: '€ 10,00' },
					{ name: 'Knoopsgaten maken', price: '€ 5,00' },
					{ name: 'Elastiek inzetten', price: '€ 11,00' },
					{ name: 'Gaatje repareren vanaf', price: '€ 7,00' },
					{ name: 'Naden repareren vanaf', price: '€ 7,00' },
					{ name: 'Scheuren repareren vanaf', price: '€ 9,00' },
					{ name: 'Drukkers plaatsen', price: '€ 3,50' },
					{ name: 'Aplicatie op stikken', price: '€ 2,50' },
				],
			},
			{
				label: 'Maatwerk',
				services: [
					{ name: 'Colbert', price: 'Op aanvraag' },
					{ name: 'Jack/Jas/Mantel', price: 'Op aanvraag' },
					{ name: 'Rok/Jurk', price: 'Op aanvraag' },
					{ name: 'Blouse/Overhemd', price: 'Op aanvraag' },
					{ name: 'Pantalon', price: 'Op aanvraag' },
					{ name: 'Motorbroek/Paard rijbroek', price: 'Op aanvraag' },
				],
			},
			{
				label: 'Gordijn',
				services: [
					{ name: 'Stof per meter', price: '€ 4,00' },
					{ name: 'Inkorten per meter', price: '€ 7,50' },
					{ name: 'Nieuwe per meter', price: '€ 15,00' },
				],
			},
		],
	},
	{
		label: 'Stomerij',
		subcategories: [
			{
				label: 'Stoomgoed',
				services: [
					{ name: 'Pantalon', price: '€ 8,50' },
					{ name: 'Colbert', price: '€ 10,00' },
					{ name: 'Overhemd / T-shirt', price: '€ 6,50' },
					{ name: 'Vest', price: 'Vanaf € 7,00' },
					{ name: 'Gillet', price: 'Vanaf € 6,50' },
					{ name: 'Stropdas', price: '€ 5,75' },
					{ name: 'Trui', price: '€ 7,00' },
					{ name: 'Rok', price: '€ 6,00' },
					{ name: 'Rok met plooien', price: '€ 10,00' },
					{ name: 'Jumpsuit', price: '€ 17,00' },
					{ name: 'Mantel', price: '€ 16,00' },
					{ name: 'Mantel (extra pluis behandeling)', price: '€ 18,00' },
					{ name: 'Regenjas / Overjas / Winterjas', price: '€ 15,00' },
					{ name: 'Regenjas / Overjas / Winterjas (dons of waterdicht)', price: '€ 19,00' },
					{ name: 'Regenjas / Overjas / Winterjas (dons EN waterdicht)', price: '€ 23,00' },
					{ name: 'Schort', price: 'Vanaf € 6,00' },
					{ name: 'Djellaba', price: 'Vanaf € 16,00' },
					{ name: 'Japon / Gewone jurk', price: '€ 13,00' },
					{ name: 'Avondjurk', price: 'T/m € 54,00' },
					{ name: 'Sjaal', price: 'Vanaf € 3,00' },
					{ name: 'Trouwjurk (altijd op eigen risico)', price: 'T/m 150,00' },
					{ name: 'Deken 1 persoons', price: '€ 19,00' },
					{ name: 'Deken 2 persoons', price: '€ 23,00' },
					{ name: 'Dekbed 1 persoons', price: '€ 22,00' },
					{ name: 'Dekbed 1 persoons  (dons of wol)', price: '€ 25,00' },
					{ name: 'Dekbed 2 persoons', price: '€ 26,00' },
					{ name: 'Dekbed 2 persoons  (dons of wol)', price: '€ 30,00' },
					{ name: 'Kussen', price: '€ 13,00' },
					{ name: 'Kussen (dons)', price: '€ 9,00' },
					{ name: 'Kussenhoes', price: '€ 7,00' },
					{ name: 'Slaapzak 1 persoons', price: '€ 22,00' },
					{ name: 'Slaapzak 1 persoons (dons)', price: '€ 27,00' },
					{ name: 'Slaapzak 2 persoons', price: '€ 26,00' },
					{ name: 'Slaapzak 2 persoons (dons)', price: '€ 30,00' },
					{ name: 'Matrashoes 1 persoons', price: '€ 26,00' },
					{ name: 'Matrashoes 2 persoons', price: '€ 30,00' },
					{ name: 'Bankhoes 2 persoons', price: '€ 21,00' },
					{ name: 'Gordijn per m2', price: '€ 5,00' },
					{ name: 'Gordijn per m2 (met voering of dubbel)', price: '€ 5,50' },
					{ name: 'Vitrage per m2', price: '€ 4,00' },
					{ name: 'Gordijn met coating per m2 (altijd op eigen risico)', price: '€ 7,00' },
					{ name: 'Laken', price: 'Vanaf € 9,00' },
					{ name: 'Ski-jas (waterdicht)', price: '€ 19,00' },
					{ name: 'Ski-broek (waterdicht)', price: '€ 15,00' },
					{ name: 'Sprei', price: '€ 25,50' },
					{ name: 'Pet (altijd op eigen risico klant)', price: '€ 5,00' },
					{ name: 'Toga', price: '€ 18,00' },
					{ name: 'Avondjurk strijken', price: '€ 31,50' },
					{ name: 'Djellaba strijken', price: '€ 10,00' },
					{ name: 'Stoelhoes 1-persoons', price: 'Vanaf € 7,00' },
					{ name: 'Topmatras', price: 'Vanaf € 36,00' },
					{ name: 'Overhemd strijken', price: '€ 4,00' },
					{ name: 'Pantalon strijken', price: '€ 4,00' },
					{ name: 'Colbert strijken', price: '€ 6,00' },
					{ name: 'Paardendeken', price: 'Vanaf € 52,00' },
					{ name: 'Extra handwassen', price: '€ 6,00' },
					{ name: 'Leren jas', price: '€ 80,00' },
					{ name: 'Leren jas (lang)', price: '€ 100,00' },
					{ name: 'Leren broek / rok / pantalon', price: 'Vanaf € 75,00' },
					{ name: 'Tapijt per m2', price: 'Vanaf € 20,00' },
					{ name: 'Geheel costuum pak', price: '€ 18,50' },
				],
			},
		],
	},
];
